version: '3.6'							# Version of docker-compose file

networks:
  default:
    name: opentelemetry-demo
    driver: bridge
    external: true
services:							    # Individual docker services for TIG
  telegraf:							    # telegraf service configuration	
    image: telegraf								
    container_name: telegraf
    restart: always   
#    user: telegraf:<host_docker_gid> ## not used in my setup, we bypass with chmod
    volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro  # Mounts telegraf.conf into the container
    - /var/run/docker.sock:/var/run/docker.sock

    ports:								# Maps port 57100 on host to container.
    - '57100:57100'


