receivers:
  hostmetrics:
    collection_interval: 30s
    scrapers:
      cpu:
      memory:

  hostmetrics/disk:
    collection_interval: 1m
    scrapers:
      disk:
      filesystem:

exporters:
  debug:
  otlphttp/prometheus:
    endpoint: "http://prometheus:9090/api/v1/otlp"
    tls:
      insecure: true

service:
  pipelines:
    metrics/infra-tel:
      receivers: [hostmetrics, hostmetrics/disk]
#      processors: [filter/ottl, transform, batch]
      exporters: [otlphttp/prometheus, debug]