#exporters:
#  logzio/traces2:
#    account_token: "QgtNbCsMTdSroLKjPjpLQTyoekelASUa"
#    region: "us-east-1"

#  prometheusremotewrite/2:
#    endpoint: "https://listener.logz.io:8053"
#    headers:
#      Authorization: "Bearer GQgPueVeGpWcqBjmOnfiEsiTrKJioFvH"

#  logzio/logs2:
#    account_token: "FUtfNsTPkCLgiaPWukXsGkhSMxOHczhH"
#    region: "us-east-1"

#processors:
#  batch:
#    send_batch_size: 10000
#    timeout: 1s

#service:
#  pipelines:
#    traces:
#      receivers: [ otlp ]
#      processors: [ batch ]
#      exporters: [ logzio/traces2, logzio/logs2, spanmetrics ]

#    metrics:
#      receivers: [ otlp, spanmetrics ]
#      exporters: [ prometheusremotewrite/2 ]

#    logs:
#      receivers: [ otlp ]
#      processors: [ batch ]
#      exporters: [ logzio/logs2 ]