version: '3.6'							# Version of docker-compose file


networks:
  default:
    name: opentelemetry-demo
    driver: bridge
    external: true
services:							    # Individual docker services for TIG

  syslog-ng:
    command: -edv
    container_name: syslog-ng
    image: balabit/syslog-ng:latest

    ports:
    - protocol: udp
      published: 514
      target: 514
    - protocol: tcp
      published: 601
      target: 601
    restart: always
    volumes:
    - ./syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf:ro

